var should = require('should');
var Artifactory = require('../../../../lib/jobs/job/publishers/artifactory.js');
var testlib = require('../../../testlib.js');

describe('Artifactory', function() {
  describe('constructor', testlib.describeProxyConstructor(Artifactory));
  describe('object', testlib.describeProxyUppableAndable(Artifactory));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'url'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'name'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'release-repo-key'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'snapshot-repo-key'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'publish-build-info'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'discard-old-builds'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'discard-build-artifacts'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'even-if-unstable'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'run-checks'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'include-publish-artifacts'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'pass-identified-downstream'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'license-auto-discovery'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'enable-issue-tracker-integration'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'aggregate-build-issues'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'allow-promotion-of-non-staged-builds'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'filter-excluded-artifacts-from-build'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'scopes'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'violation-recipients'));
  describe('properties', testlib.describeProxyPrimitiveArrayProperty(Artifactory, 'matrix-params'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'black-duck-app-name'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'black-duck-app-version'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'black-duck-report-recipients'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'black-duck-scopes'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'black-duck-run-checks'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'black-duck-include-published-artifacts'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'auto-create-missing-component-requests'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'auto-discard-stale-component-requests'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'deploy-artifacts'));
  describe('properties', testlib.describeProxyPrimitiveArrayProperty(Artifactory, 'deployment-include-patterns'));
  describe('properties', testlib.describeProxyPrimitiveArrayProperty(Artifactory, 'deployment-exclude-patterns'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Artifactory, 'env-vars-include'));
  describe('properties', testlib.describeProxyPrimitiveArrayProperty(Artifactory, 'env-vars-include-patterns'));
  describe('properties', testlib.describeProxyPrimitiveArrayProperty(Artifactory, 'env-vars-exclude-patterns'));
});
