"use strict";

var util = require('../../../misc/util.js');

uppableObjectProxy(Artifactory)
primitive(util, Artifactory, 'url')
primitive(util, Artifactory, 'name')
primitive(util, Artifactory, 'release-repo-key')
primitive(util, Artifactory, 'snapshot-repo-key')
primitive(util, Artifactory, 'publish-build-info')
primitive(util, Artifactory, 'discard-old-builds')
primitive(util, Artifactory, 'discard-build-artifacts')
primitive(util, Artifactory, 'even-if-unstable')
primitive(util, Artifactory, 'run-checks')
primitive(util, Artifactory, 'include-publish-artifacts')
primitive(util, Artifactory, 'pass-identified-downstream')
primitive(util, Artifactory, 'license-auto-discovery')
primitive(util, Artifactory, 'enable-issue-tracker-integration')
primitive(util, Artifactory, 'aggregate-build-issues')
primitive(util, Artifactory, 'allow-promotion-of-non-staged-builds')
primitive(util, Artifactory, 'filter-excluded-artifacts-from-build')
primitive(util, Artifactory, 'scopes')
primitive(util, Artifactory, 'violation-recipients')
primitiveArray(util, Artifactory, 'matrix-params')
primitive(util, Artifactory, 'black-duck-app-name')
primitive(util, Artifactory, 'black-duck-app-version')
primitive(util, Artifactory, 'black-duck-report-recipients')
primitive(util, Artifactory, 'black-duck-scopes')
primitive(util, Artifactory, 'black-duck-run-checks')
primitive(util, Artifactory, 'black-duck-include-published-artifacts')
primitive(util, Artifactory, 'auto-create-missing-component-requests')
primitive(util, Artifactory, 'auto-discard-stale-component-requests')
primitive(util, Artifactory, 'deploy-artifacts')
primitiveArray(util, Artifactory, 'deployment-include-patterns')
primitiveArray(util, Artifactory, 'deployment-exclude-patterns')
primitive(util, Artifactory, 'env-vars-include')
primitiveArray(util, Artifactory, 'env-vars-include-patterns')
primitiveArray(util, Artifactory, 'env-vars-exclude-patterns')
