"use strict";

var util = require('../../../misc/util.js');

uppableObjectProxy(EmailExt)
primitive(util, EmailExt, 'recipients')
primitive(util, EmailExt, 'reply-to')
primitive(util, EmailExt, 'content-type')
primitive(util, EmailExt, 'subject')
primitive(util, EmailExt, 'body')
primitive(util, EmailExt, 'attach-build-log')
primitive(util, EmailExt, 'attachments')
primitive(util, EmailExt, 'always')
primitive(util, EmailExt, 'unstable')
primitive(util, EmailExt, 'first-failure')
primitive(util, EmailExt, 'not-built')
primitive(util, EmailExt, 'aborted')
primitive(util, EmailExt, 'regression')
primitive(util, EmailExt, 'failure')
primitive(util, EmailExt, 'second-failure')
primitive(util, EmailExt, 'improvement')
primitive(util, EmailExt, 'still-failing')
primitive(util, EmailExt, 'success')
primitive(util, EmailExt, 'fixed')
primitive(util, EmailExt, 'still-unstable')
primitive(util, EmailExt, 'pre-build')
primitive(util, EmailExt, 'presend-script')
primitive(util, EmailExt, 'save-output')
primitive(util, EmailExt, 'matrix-trigger')
primitiveArray(util, EmailExt, 'send-to')
