var should = require('should');
var Job = require('../../lib/jobs/job.js');
var testlib = require('../testlib.js');
var Maven = require('../../lib/jobs/job/maven.js');
var Wrappers = require('../../lib/jobs/job/wrappers.js');
var Builders = require('../../lib/jobs/job/builders.js');
var Hipchat = require('../../lib/jobs/job/hipchat.js');
var ExecutionStrategy = require('../../lib/jobs/job/execution-strategy.js');
var Axes = require('../../lib/jobs/job/axes.js');
var Metadata = require('../../lib/jobs/job/metadata.js');
var Notifications = require('../../lib/jobs/job/notifications.js');
var Parameters = require('../../lib/jobs/job/parameters.js');
var Properties = require('../../lib/jobs/job/properties.js');
var Publishers = require('../../lib/jobs/job/publishers.js');
var Reporters = require('../../lib/jobs/job/reporters.js');
var Scm = require('../../lib/jobs/job/scm.js');
var Triggers = require('../../lib/jobs/job/triggers.js');

describe('Job', function() {
  describe('constructor', testlib.describeProxyConstructor(Job));
  describe('object', testlib.describeProxyUppableAndable(Job));
  describe('properties', testlib.describeProxyPrimitiveProperty(Job, 'name'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Job, 'description'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Job, 'node'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Job, 'project-type'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Job, 'dsl'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Job, 'needs-workspace'));
  describe('properties', testlib.describeProxyPrimitiveProperty(Job, 'dsl-file'));
  describe('properties', testlib.describeProxyObjectProperty(Job, 'maven', Maven));
  describe('properties', testlib.describeProxyCustomArrayProperty(Job, 'wrappers', Wrappers));
  describe('properties', testlib.describeProxyCustomArrayProperty(Job, 'builders', Builders));
  describe('properties', testlib.describeProxyObjectProperty(Job, 'hipchat', Hipchat));
  describe('properties', testlib.describeProxyObjectProperty(Job, 'execution-strategy', ExecutionStrategy));
  describe('properties', testlib.describeProxyCustomArrayProperty(Job, 'axes', Axes));
  describe('properties', testlib.describeProxyCustomArrayProperty(Job, 'metadata', Metadata));
  describe('properties', testlib.describeProxyCustomArrayProperty(Job, 'notifications', Notifications));
  describe('properties', testlib.describeProxyCustomArrayProperty(Job, 'parameters', Parameters));
  describe('properties', testlib.describeProxyCustomArrayProperty(Job, 'properties', Properties));
  describe('properties', testlib.describeProxyCustomArrayProperty(Job, 'publishers', Publishers));
  describe('properties', testlib.describeProxyCustomArrayProperty(Job, 'reporters', Reporters));
  describe('properties', testlib.describeProxyCustomArrayProperty(Job, 'scm', Scm));
  describe('properties', testlib.describeProxyCustomArrayProperty(Job, 'triggers', Triggers));
});
